version: "3.9"

services:
  postgres:
    image: postgres:15
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runner
    ports:
      - 3000:3000
    env_file:
      - packages/backend/.env
    links:
      - postgres
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: bot-runner
    links:
      - backend
    env_file:
      - packages/bot/.env

volumes:
  postgres-data:
