version: "3.9"

services:
  postgres:
    image: postgres:15
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    hostname: redis

    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

<<<<<<< Updated upstream
=======
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - 3000:3000
    env_file:
      - packages/backend/.env

>>>>>>> Stashed changes
volumes:
  postgres-data:
  redis-data:
