[package]
name = "desktop"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "=2.0.0-rc.3", features = [] }

[dependencies]
tauri = { version = "=2.0.0-rc.3", features = ["devtools"] }
tauri-plugin-shell = "=2.0.0-rc.1"
serde_json = "=1.0.125"
tauri-plugin-websocket = "=2.0.0-rc.0"
tauri-plugin-http = { version = "=2.0.0-rc.0", features = ["rustls-tls"] }
tauri-plugin-window-state = "=2.0.0-rc.1"
tauri-plugin-deep-link = "=2.0.0-rc.1"
tauri-plugin-notification = "=2.0.0-rc.1"
tauri-plugin-process = "=2.0.0-rc.0"
log = "0.4"
tauri-plugin-log = "=2.0.0-rc.0"
url = "2.5.2"
tauri-plugin-store = "2.0.0-rc"
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "=2.0.0-rc.1"
tauri-plugin-single-instance = "2.0.0-rc"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
