services:
  postgres:
    image: postgres
    hostname: postgres
    env_file: .env
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      tduattendance:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  tduattendance:
