version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    network_mode: service:core

  postgres:
    image: postgres:14
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    networks:
      attendance_frontend_devcontainer:
        aliases:
          - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    hostname: redis
    networks:
      attendance_frontend_devcontainer:
        aliases:
          - redis
    restart: unless-stopped

  core:
    depends_on:
      - postgres
      - redis
    image: ghcr.io/team3132/tduattendance:1.3.2
    env_file: .env
    networks:
      attendance_frontend_devcontainer:
        aliases:
          - core

volumes:
  postgres-data:

networks:
  attendance_frontend_devcontainer:
