version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    user: 1000:1000
    links:
      - postgres
      - redis

  postgres:
    image: postgres:14
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    hostname: redis

    restart: unless-stopped
    volumes:
      - redis-data:/data
    

volumes:
  postgres-data:
  redis-data:
