services:
  postgres:
    image: postgres
    hostname: postgres
    env_file: .env
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      tduattendance:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      tduattendance:
    restart: unless-stopped

networks:
  tduattendance:
