on:
  workflow_call:

name: Check

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependancies
        run: yarn install --frozen-lockfile
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/tsc.json"
      - name: Type Check Backend
        run: yarn typecheck
  backend-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install Dependancies
        run: yarn install --frozen-lockfile
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/eslint-stylish.json"
      - name: Lint
        run: yarn lint:backend
