on:
  workflow_call:

name: Lint

jobs:
  backend-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install --frozen-lockfile
      - name: Generate
        run: yarn workspace backend prisma generate
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/eslint-stylish.json"
      - name: Lint
        run: yarn lint:backend
