on:
  workflow_call:

name: Check

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "pnpm"
      - name: Install Dependancies
        run: pnpm install --frozen-lockfile
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/tsc.json"
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/eslint-stylish.json"

      - name: Type Check Backend
        run: pnpm backend typecheck

      - name: Build Backend
        run: pnpm backend build

      - name: Type Check Frontend
        run: pnpm frontend typecheck
      - name: Type Check Bot
        run: pnpm bot typecheck
