on:
  workflow_call:

name: Check

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install Dependancies
        run: pnpm install --frozen-lockfile

      - name: Build Backend
        run: pnpm run --filter frontend build
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/tsc.json"
      - name: Type Check Packages
        run: pnpm typecheck
