name: Release

on:
  release:
    types: ['released']
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: The version to publish

jobs:
  type-check:
    uses: ./.github/workflows/job-tscheck.yml
  lint:
    uses: ./.github/workflows/job-eslint.yml
  build-backend:
    name: Build
    runs-on: ubuntu-latest
    needs: [type-check, lint]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install --frozen-lockfile
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/team3132/attendancesystem
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        id: docker_build
        with:
          push: true
          context: .
          file: backend.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build-deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [type-check, lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependancies
        run: yarn install
      - name: Build
        run: yarn build:frontend
      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish packages/frontend/dist --project-name=attendancefrontend

